version: "2"
services:
  mq:
    image: rabbitmq:3.7.8-management
    restart: always
    mem_limit: 2g
    container_name: mq1
    hostname: mq1
    volumes:
      - ./mnesia:/var/lib/rabbitmq/mnesia
    ports:
      - "55672:15672"
      - "56720:5672"
    environment:
      - CONTAINER_NAME=rabbitMQ
      - RABBITMQ_ERLANG_COOKIE=3t182q3wtj1p9z0kd3tb
      - RABBITMQ_DEFAULT_USER=local_test
      - RABBITMQ_DEFAULT_PASS=DkqkuGkOsBTzKtMt
